PreserveThreading=true
[whatsapp]
	[whatsapp.valariz]		
		Number="+19252319604"
		SessionFile="session-19252319604.gob"
		QrOnWhiteTerminal=false
		RemoteNickFormat="[{PROTOCOL}] @{NICK}: "
        
[[gateway]]
name="gateway1"
enable=true

	[[gateway.inout]]
    account="whatsapp.valariz"
    channel="beta tester"
