# / 
# SERVERS
# / 
[telegram]
    [telegram.valariz]
        Token="${TELEGRAM_VALARIZ_TOKEN}"
        RemoteNickFormat="<{NICK}> " # How your message will be formatted when bridged. 
        MessageFormat="HTMLNick :"
        QuoteFormat="{MESSAGE} (re @{QUOTENICK}: {QUOTEMESSAGE})"
        QuoteLengthLimit=46 # Truncuate long quotes to prevent spammy bridged messages
        IgnoreMessages="^/" # Don't bridge bot commands (as the responses will not be bridged)
[discord]
	[discord.valariz]
		Token="${DISCORD_VALARIZ_TOKEN}"
		Server="${DISCORD_VALARIZ_SERVER}" # picked from guilds the bot is connected to
		RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
[whatsapp]
	[whatsapp.valariz]		
		Number="${WHATSAPP_VALARIZ_NUMBER}"
		SessionFile="${WHATSAPP_VALARIZ_SESSIONFILE}"
		QrOnWhiteTerminal=false
		RemoteNickFormat="[{PROTOCOL}] @{NICK}: "
		
# Map threads from other bridges on discord replies
PreserveThreading=true

# / 
# GATEWAYS
# / 
[[gateway]]
name="gateway1"
enable=true

    [[gateway.inout]]
    account="telegram.valariz"
    channel="-1001824836940"

    [[gateway.inout]]
    account="discord.valariz"
    channel="ID:749625005633044494"
	
    [[gateway.inout]]
    account="whatsapp.valariz"
    channel="120363076904021773@g.us", "" 
