# / 
# SERVERS
# / 
[telegram]
    [telegram.valariz]
        Token="${TELEGRAM_VALARIZ_TOKEN}"
	RemoteNickFormat="<{NICK}> "
        MessageFormat="HTMLNick :"
        QuoteFormat="{MESSAGE} (re @{QUOTENICK}: {QUOTEMESSAGE})"
        QuoteLengthLimit=46 # Truncuate long quotes to prevent spammy bridged messages
        IgnoreMessages="^/" # Don't bridge bot commands (as the responses will not be bridged)
[discord]
	[discord.valariz]
		Token="${DISCORD_VALARIZ_TOKEN}"
		Server="${DISCORD_VALARIZ_SERVER}" # picked from guilds the bot is connected to
		#RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
	##[discord.valarizz]
		##Token="${DISCORD_VALARIZZ_TOKEN}"
		##Server="${DISCORD_VALARIZZ_SERVER}" # picked from guilds the bot is connected to
		#RemoteNickFormat="<{NICK}> "
[whatsapp]
	[whatsapp.valariz]		
		Number="${WHATSAPP_VALARIZ_NUMBER}"
		SessionFile="${WHATSAPP_VALARIZ_SESSIONFILE}"
		QrOnWhiteTerminal=false
# Map threads from other bridges on discord replies
PreserveThreading=true

# / 
# GATEWAYS
# / 
[[gateway]]
name="gateway1"
enable=false

    [[gateway.inout]]
    account="telegram.valariz"
    channel="-1001824836940"

    [[gateway.inout]]
    account="discord.valariz"
    channel="ID:749625005633044494"
	
    [[gateway.inout]]
    account="whatsapp.valariz"
    channel= "120363045095042105@g.us"

	
[[gateway]]
name="gateway2"
enable=false	

    [[gateway.inout]]
    account="telegram.valariz"
    channel="-1001919850360"

    [[gateway.inout]]
    account="discord.valariz"
    channel="ID:838585639254360135"
	
    [[gateway.inout]]
    account="whatsapp.valariz"
    channel= "120363033109596282@g.us"

[[gateway]]
name="gateway3"
enable=false	

    [[gateway.out]]
    account="discord.valarizz"
    channel="ID:1094620047751790733"
	
    [[gateway.in]]
    account="whatsapp.valariz"
    channel= "120363045095042105@g.us"
    
[[gateway]]
name="gateway4"
enable=true

    [[gateway.inout]]
    account="discord.valariz"
    channel="ID:740032411034976386"
	
    [[gateway.inout]]
    account="telegram.valariz"
    channel="-1001801183046"

[[gateway]]
name="gateway5"
enable=true

    [[gateway.inout]]
    account="discord.valariz"
    channel="ID:1282861721832128594"
	
    [[gateway.inout]]
    account="telegram.valariz"
    channel="-1002298058811"

    [[gateway.inout]]
    account="whatsapp.valariz"
    channel= "120363298703850155@g.us"

[[gateway]]
name="gateway6"
enable=true

    [[gateway.inout]]
    account="telegram.valariz"
    channel="-1004567613774"

    [[gateway.inout]]
    account="whatsapp.valariz"
    channel= "120363290871521706@g.us"
